import os
import shutil
import numpy as np
import warnings
import multiprocessing as mproc
import subprocess
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit import RDLogger
from rdkit.Chem import rdchem
from subprocess import PIPE
from pymatgen.core.periodic_table import Specie, Element
from pymatgen.core.structure import Molecule

RDLogger.DisableLog('rdApp.*')
warnings.filterwarnings('ignore')

os.makedirs('output_for_assembly',exist_ok=True)

nodes = ['Zr6']
# change to the line below to reproduce paper result
# nodes = [i.split('_')[1].split('.sdf')[0] for i in os.listdir('data/conformers') if 'conformers' in i]

NCPUS = int(0.9*os.cpu_count())

def add_Hs(base_dir, file, smiles, xyz_H_dir, node):
    if not file.startswith('.'):
        mol_num = file.split('_')[1]
        sample_num = file.split('_')[2]
        # generate smile strings
        cmd = ['obabel', os.path.join(base_dir, file), '-osmi']
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        output = result.stdout.split()[0]
        # remove square brackets
        result = output.replace('[','').replace(']','')
        smiles.append(result)
    
    if '@' not in result:
        try:
            # generate 3D coordinates with hydrogens using RDKit
            target_xyz_path = os.path.join(xyz_H_dir, node, f'mol_{mol_num}_{sample_num}.xyz')
            
            os.makedirs(os.path.dirname(target_xyz_path), exist_ok=True)
            
            mol = Chem.MolFromSmiles(result)
            if mol is None:
                print(f"Failed to parse SMILES: {result}")
                return
            
            mol = Chem.AddHs(mol)
            
            status = AllChem.EmbedMolecule(mol, randomSeed=42)
            if status != 0:
                print(f"3D embedding failed for SMILES: {result}")
                return
            
            AllChem.MMFFOptimizeMolecule(mol)
            
            with open(target_xyz_path, 'w') as f:
                f.write(f"{mol.GetNumAtoms()}\n")
                f.write(f"Generated by RDKit from SMILES: {result}\n")
                
                conf = mol.GetConformer()
                for i in range(mol.GetNumAtoms()):
                    pos = conf.GetAtomPosition(i)
                    atom = mol.GetAtomWithIdx(i)
                    symbol = atom.GetSymbol()
                    f.write(f"{symbol} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}\n")
            
            if os.path.exists(target_xyz_path):
                with open(target_xyz_path, 'r') as f:
                    info = f.read()
                if 'nan' in info:
                    os.remove(target_xyz_path)
                    print(f"Removed invalid structure: {target_xyz_path}")
                else:
                    print(f"Successfully generated: {target_xyz_path}")
            else:
                print(f"Failed to generate: {target_xyz_path}")
                
        except Exception as e:
            print(f"Unexpected error in RDKit processing: {e}")

def generate_dummy_atoms(file, xyz_H_dir, xyz_X_dir, node):
    if not file.startswith('.'):
        try:
            # get smiles string of molecule
            mol_smiles = subprocess.run(f'obabel {os.path.join(xyz_H_dir,node,file)} -osmi', shell=True, stdout=PIPE, stderr=PIPE, universal_newlines=True).stdout.split()[0]
            mol_smiles = mol_smiles.replace('[','').replace(']','')
            carboxylic = Chem.MolFromSmarts('[O;H,-]C=O') # check carboxylic group
            Chem.SetGenericQueriesFromProperties(carboxylic)
            list_carboxylic = Chem.MolFromSmiles(mol_smiles).GetSubstructMatches(carboxylic)
            
            # process carboxylic group
            if len(list_carboxylic) > 0:
                molecule = Molecule.from_file(os.path.join(xyz_H_dir,node,file))
                O_id_remove = [] # ids of O atoms to be removed
                H_id_remove = [] # ids of H atoms attached to O atom in -COOH to be removed
                for site_id in range(len(molecule)):
                    if molecule[site_id].specie.symbol == "C":
                        neighbor_sites = molecule.get_neighbors(molecule[site_id],1.5)
                        neighbor_elements = []
                        for site in neighbor_sites:
                            neighbor_elements.append(site.specie.symbol)
                        if set(neighbor_elements) == set(['C','O','O']):
                            # substitute -C by -At
                            molecule[site_id].species = Element('At')
                            # append O_id_remove
                            for s in neighbor_sites:
                                if s.specie.symbol == 'O':
                                    for i,site in enumerate(molecule.sites):
                                        if list(site.coords) == list(s.coords):
                                            O_id_remove.append(i)

                if len(O_id_remove) == 4:
                    # append H_id_remove
                    for O_id in O_id_remove:
                        neighbor_site_O = molecule.get_neighbors(molecule[O_id],1.2)
                        for i,site in enumerate(molecule.sites):
                            try:
                                if list(site.coords) == list(neighbor_site_O[0].coords) and site.specie.symbol == 'H':
                                    H_id_remove.append(i)
                            except:
                                pass
                    molecule.remove_sites(O_id_remove+H_id_remove)
                    # write to new xyz
                    if len(O_id_remove) == 4 and len(H_id_remove) == 2:
                        molecule.to(os.path.join(xyz_X_dir,node,file))
        except:
            pass
if __name__ == '__main__':   
    for node in nodes:
        # for n_atoms in [5]:
    # change to the line below to reproduce paper result
        for n_atoms in range(5,11):
            print(f'Now on n_atom: {n_atoms} node: {node}')
            base_dir = f'output/n_atoms_{n_atoms}/{node}/'
            xyz_H_dir = f'output_for_assembly/n_atoms_{n_atoms}/xyz_h/'
            os.makedirs(xyz_H_dir,exist_ok=True)
            xyz_X_dir = f'output_for_assembly/n_atoms_{n_atoms}/xyz_X/'
            os.makedirs(xyz_X_dir,exist_ok=True)
            if len(os.listdir(base_dir)) > 0: # results not empty
                if not os.path.exists(os.path.join(xyz_H_dir,node)):
                    # add hydrogens
                    print(f'Adding Hs...')
                    smiles = []
                    os.makedirs(os.path.join(xyz_H_dir,node),exist_ok=True)
                    with mproc.Pool(NCPUS) as mp:
                        mp.starmap_async(add_Hs, [(base_dir, file, smiles, xyz_H_dir, node) for file in os.listdir(base_dir)]).get()
                        #mp.map_async(add_Hs, os.listdir(base_dir)).get()    

                # add dummy atoms
                print(f'Adding dummy atoms...')
                os.makedirs(os.path.join(xyz_X_dir,node),exist_ok=True)
                with mproc.Pool(NCPUS) as mp:
                    mp.starmap_async(generate_dummy_atoms, [(file, xyz_H_dir, xyz_X_dir, node) for file in os.listdir(os.path.join(xyz_H_dir, node))]).get()
                    #mp.map_async(generate_dummy_atoms, os.listdir(os.path.join(xyz_H_dir,node))).get()